### ISSUE TITLE
No command to say poop in background forever ))<>((

### ISSUE THREAD

**Issue by mlauter** [lh00000000/modern-utils#1]
this good stuff here in your library but missing important
.

**Comment by lh00000000** [comment]
ah how could I forgotten. 
fixed in https://github.com/lh00000000/modern-utils/commit/90eacd4c36755496cd06d0eb77c5891bb6d6ffcb

**Comment by lh00000000** [comment]
how do i close this

**Comment by lh00000000** [comment]
oh
